#!/bin/sh

# Set up them keybinds...
export SXHKD_SHELL=sh # This should prevent lag
sxhkd &

# Set up the monitor
~/randr

#Sauce: https://old.reddit.com/r/unixporn/comments/5lxecy/bspwm_with_two_monitors/dbzciek/
i=0
n=`bspc query -M | wc -l`  # count number of lines in bspwm's monitor list
per=$(( 10 / n ))          # number of desktops per monitor
for monitor in `bspc query -M`; do
    bspc monitor $monitor -d `seq $i $(( i + per - 1 ))` 
    # seq is end-inclusive; `seq 1 $((1+2))` returns "1 2 3"
    i=$(( i + per ))
done

#bspwm config
bspc config border_width         2
bspc config window_gap          15
bspc config bottom_padding	45

bspc config split_ratio          	0.52
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_follows_pointer	true

bspc config external_rules_command	~/.config/bspwm/external_rules

bspc rule -a Origin.exe floating=on
bspc rule -a origin.exe floating=on

#autostart
xsetroot -cursor_name left_ptr
setxkbmap -option caps:escape
wpg -m
polybar tray &
picom &
dunst &
export STEAM_FRAME_FORCE_CLOSE=1
~/.config/polybar/launch.sh &
~/autorun.sh
