# Shell variables
# Generated by 'wal'
wallpaper='katamari.png'

# Special
background='#2d3232'
foreground='#ffffcb'
cursor='#ffffcb'

# Colors
color0='#2d3232'
color1='#0a669f'
color2='#0b4371'
color3='#e4a130'
color4='#e95365'
color5='#6d9516'
color6='#a63226'
color7='#d1d099'
color8='#515b5b'
color9='#0187d9'
color10='#06579b'
color11='#ffd52c'
color12='#ff5773'
color13='#91cc11'
color14='#e53624'
color15='#ffffcb'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
